import { Poppins } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/components/theme-provider';
import StoreProvider from '@/context/StoreProvider';

const geistPoppins = Poppins({
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'AI-Chat Interface',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={`${geistPoppins.variable} antialiased min-h-screen`}>
        <StoreProvider>
          <ThemeProvider attribute='class' defaultTheme='light'>
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
